### ISSUE TITLE
Last Will delivery fails - info->will_length not populated

### ISSUE THREAD

**Issue by TAMHAN** [tuanpmt/espmqtt#15]
Hello,
this is just a small thing - I just looked at the MQTT message file:

```
    if (info->will_topic != NULL && info->will_topic[0] != '\0')
    {
ESP_LOGW("TAM", "WANT TO APPEND");
ESP_LOGW("TAM", "WANT TO APPEND %s %d", info->will_message, info->will_length);

        if (append_string(connection, info->will_topic, strlen(info->will_topic)) < 0)
            return fail_message(connection);

        if (append_string(connection, info->will_message, strlen(info->will_message)) < 0)
            return fail_message(connection);

ESP_LOGW("TAM", "APPEND DONE");
```

This version works. However, will_length always is zero, causing the registration of the payload to fail when tested against Mosquitto. I totally suck at GitHub, and thus dont know how to upload a fix - but if anyone of you has problems with the last will not being sent on the ESP32 with Mosquitto, here is the solution...I replaced will_length with strlen blahblah in the second call to append_string.

**Comment by tuanpmt** [comment]
Thank you @TAMHAN 
It will resolve in new version of espmqtt: https://github.com/tuanpmt/espmqtt/blob/feature/outbox/mqtt_client.c#L126
