### ISSUE TITLE
Changing config values

### ISSUE THREAD

**Issue by kylehendricks** [tuanpmt/espmqtt#19]
I see that Kconfig was removed.  Is there currently a good way to modify config values without changing the espmqtt source?

**Comment by tijnkooijmans** [comment]
Yes please restore the Kconfig.

**Comment by tijnkooijmans** [comment]
@kylehendricks , you can also config in your main component.mk by adding for example CPPFLAGS += -DMQTT_MAX_PASSWORD_LEN=64

**Comment by tuanpmt** [comment]
Check this: https://github.com/tuanpmt/espmqtt/commit/0d4d269dc357c51bb53070779da37b3c5ddadaf3
