### ISSUE TITLE
Guru Meditation Error

### ISSUE THREAD

**Issue by AmrutaCh** [tuanpmt/espmqtt#21]
ESP-idf version- v3.1-dev-239-g1c3dd23f
MQTT server- local mosquitto server

Hello,
I am using mqtt-tcp example and modified it as below:
`esp_mqtt_client_config_t mqtt_cfg = {
    .event_handle = mqtt_event_handler,
    .host = "192.168.1.9",
    .port = 1883, 
    .client_id = "mqtt_client_id",
    .username = "user",
    .password = "password",
    .keepalive = 10,
    .lwt_topic = "/lwt",
    .lwt_msg = "offline",
    .lwt_qos = 2,
    .lwt_retain = 0,
};`

Its crashing while connecting to server
`
[0;32mI (137) MQTT_SAMPLE: [APP] Startup..[0m
[0;32mI (137) MQTT_SAMPLE: [APP] Free memory: 274420 bytes[0m
[0;32mI (147) MQTT_SAMPLE: [APP] IDF version: v3.1-dev-239-g1c3dd23-dirty[0m
I (187) wifi: wifi firmware version: 403db1d
I (187) wifi: config NVS flash: enabled
I (187) wifi: config nano formating: disabled
[0;32mI (187) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
[0;32mI (197) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
I (227) wifi: Init dynamic tx buffer num: 32
I (227) wifi: Init data frame dynamic rx buffer num: 32
I (227) wifi: Init management frame dynamic rx buffer num: 32
I (237) wifi: wifi driver task: 3ffc08ac, prio:23, stack:4096
I (237) wifi: Init static rx buffer num: 10
I (237) wifi: Init dynamic rx buffer num: 32
I (247) wifi: wifi power manager task: 0x3ffc54ec prio: 21 stack: 2560
[0;32mI (257) MQTT_SAMPLE: start the WIFI SSID:[ExploreEmbedded] password:[******][0m
[0;32mI (287) phy: phy_version: 366.0, ba9923d, Dec 29 2017, 14:25:06, 0, 0[0m
I (287) wifi: mode : sta (24:0a:c4:00:20:9e)
[0;32mI (287) MQTT_SAMPLE: Waiting for wifi[0m
I (657) wifi: n:3 1, o:1 0, ap:255 255, sta:3 1, prof:1
I (1637) wifi: state: init -> auth (b0)
I (1637) wifi: state: auth -> assoc (0)
I (1647) wifi: state: assoc -> run (10)
I (1717) wifi: connected with ExploreEmbedded, channel 3
I (4647) wifi: pm start, type:0

[0;32mI (5087) event: sta ip: 192.168.1.10, mask: 255.255.255.0, gw: 192.168.1.1[0m
D (5087) MQTT_CLIENT: MQTT client_id=mqtt_client_id[0m
D (5087) TRANSPORT_TCP: [sock=4096],connecting to server IP:192.168.1.9,Port:1883...[0m
Guru Meditation Error: Core  1 panic'ed (LoadProhibited)
. Exception was unhandled.
Register dump:
PC      : 0x400014fd  PS      : 0x00060d30  A0      : 0x8012d2b0  A1      : 0x3ffc8830  
A2      : 0x00000000  A3      : 0xfffffffc  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffc87e0  
A10     : 0x00000000  A11     : 0x3f40b597  A12     : 0x3ffc8a74  A13     : 0x3ffae8d8  
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x400014fd:0x3ffc8830 0x4012d2ad:0x3ffc8840 0x4012eaa9:0x3ffc8b50 0x40083151:0x3ffc8b80 0x4010cb47:0x3ffc8bd0
`

Any helps will be greatly appreciated

**Comment by AmrutaCh** [comment]
Found the issue. It crashes at L649 in mqtt_client.c. It may be because of `client->config->scheme` remains uninitialized when uri is not used in mqtt client but setting it to `null` didn't work. Removing `client->config->scheme` from the log at L649 solved the issue.

**Comment by tuanpmt** [comment]
Thank you @AmrutaCh 

I've updated the library to add default scheme, instead remove it
