### ISSUE TITLE
Interference when using with Mongoose

### ISSUE THREAD

**Issue by nathanprins** [tuanpmt/espmqtt#56]
I'm using this library in conjunction with Cesanta's Mongoose library in order to serve html and connect to an MQTT broker at the same time. Both libraries work independently, but together they don't.

I'm getting this error: 
```
I (61964) MQTT_CLIENT: Sending MQTT CONNECT message, type: 1, id: 0000
E (61965) MQTT_CLIENT: Writing failed, errno= 4
I (61966) MQTT_CLIENT: Error MQTT Connected
I (61972) MQTT_CLIENT: Reconnect after 10000 ms
I (61976) MQTT_SAMPLE: MQTT_EVENT_DISCONNECTED
```
In this case the HTTP server works, but after a while the MQTT client connects and the HTTP server stops working.
I've tried numerous things but nothing seems to work. 
Stopping the `mg_mgr_poll`, which polls for HTTP request, works but then of course the HTTP server doesn't respond.
I think the 2 sockets are interfering.
Thanks in advance

**Comment by tuanpmt** [comment]
@nathanprins Please try this fix:

https://github.com/tuanpmt/espmqtt/issues/48#issuecomment-393199625

**Comment by nathanprins** [comment]
That worked a treat! Thank you very much. Made my day!
